import type { Metadata } from "next";
import { DotGothic16, Major_Mono_Display } from "next/font/google";
import "./globals.css";

const dotGothic16 = DotGothic16({
  weight: "400",
  variable: "--font-dotgothic16",
  subsets: ["latin"],
});

const majorMonoDisplay = Major_Mono_Display({
  weight: "400",
  variable: "--font-majormonodisplay",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dotGothic16.variable} ${majorMonoDisplay.variable} antialiased`}
        style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
